services:
  mysql-db:
    image: mysql:8.0
    container_name: food_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      timeout: 10s
      retries: 5
      start_period: 30s

  redis-cache:
    image: redis:7.0-alpine
    container_name: food_redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: food_app
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
      redis-cache:
        condition: service_started
    env_file:
      - .env
    environment:
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json
    restart: on-failure

  ngrok:
    image: ngrok/ngrok:latest
    container_name: food_ngrok
    restart: unless-stopped
    command:
      - "http"
      - "app:8080"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - app

  minio:
    image: minio/minio:latest
    container_name: food_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  mysql_data:
  minio_data: