server:
  port: 8080

spring:
  application:
    name: food-management-system

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: HS512

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

zalo-pay:
  app-id: ${ZALOPAY_APP_ID}
  key1: ${ZALOPAY_KEY1}
  key2: ${ZALOPAY_KEY2}
  create-order-url: "https://sb-openapi.zalopay.vn/v2/create"
  order-status-url: "https://sb-openapi.zalopay.vn/v2/query"
  redirect-url: "http://localhost:5173/payment-result"
  callback-url: "http://localhost:8080/zalopay/callback"

openapi:
  service:
    url: ${SWAGGER_SERVER_URL:http://localhost:8080}

minio:
  url: http://localhost:9000
  # url: http://minio:9000 # (Nếu chạy app trong docker thì dùng cái này)
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: food-media

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900
  refresh-token-expiration: 604800
  refresh-token-remember-me-expiration: 2592000